# Generated by Django 5.2.16 on 2026-07-20 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('HR', 'HR'), ('TECHNICAL', 'Technical'), ('MIXED', 'Mixed')], max_length=20)),
                ('experience', models.CharField(choices=[('FRESHER', 'Fresher'), ('LOW', 'Low(1-2 Years)'), ('MID', 'Mid(3-5 Years)'), ('HIGH', 'High(6-10 Years)')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], max_length=20)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('number_of_questions', models.PositiveIntegerField(blank=True, max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('expected_answer', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True)),
                ('score', models.PositiveIntegerField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interviews.question')),
            ],
        ),
    ]
