# Generated by Django 5.2.16 on 2026-07-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='number_of_questions',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
