# Generated by Django 5.2.16 on 2026-07-24 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_interviewsession_number_of_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='filler_words',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='words_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interviews.question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
