# Generated by Django 5.2.16 on 2026-08-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_useranswer_duration_useranswer_filler_words_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
