# Generated by Django 5.2.16 on 2026-08-15 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_alter_useranswer_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='reference_photo',
            field=models.ImageField(blank=True, null=True, upload_to='reference_photos/'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='termination_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('NO_FACE', 'No Face Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('DEVICE_DETECTED', 'Electronic Device Detected'), ('FACE_MISMATCH', 'Face Mismatch'), ('FULLSCREEN_EXIT', 'Exited Fullscreen'), ('LOW_GAZE', 'Looking Away')], max_length=30)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='interviews.interviewsession')),
            ],
        ),
    ]
